// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:footy_vision_frontend/config/environments.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Environments.apiKeyWeb,
    appId: Environments.appIdWeb,
    messagingSenderId: Environments.messagingSenderId,
    projectId: Environments.projectId,
    authDomain: Environments.authDomain,
    storageBucket: Environments.storageBucket,
    measurementId: Environments.measurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Environments.apiKeyAndroid,
    appId: Environments.appIdAndroid,
    messagingSenderId: Environments.messagingSenderId,
    projectId: Environments.projectId,
    storageBucket: Environments.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Environments.apiKeyIos,
    appId: Environments.appIdIos,
    messagingSenderId: Environments.messagingSenderId,
    projectId: Environments.projectId,
    storageBucket: Environments.storageBucket,
    iosBundleId: Environments.iosBundleId,
  );
}
